-- MySQL Script generated by MySQL Workbench
-- 08/08/19 10:13:20
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`usuario` ;

CREATE TABLE IF NOT EXISTS `blog`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  `senha` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `img` VARCHAR(50) CHARACTER SET 'utf8' DEFAULT 'user1.jpg',
  `sobre` VARCHAR(300) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`categoria` ;

CREATE TABLE IF NOT EXISTS `blog`.`categoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`post` ;

CREATE TABLE IF NOT EXISTS `blog`.`post` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  `descricao` VARCHAR(300) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `img` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT 'img0.jpg',
  `datacadastro` DATETIME NOT NULL,
  `texto` TEXT CHARACTER SET 'utf8' NOT NULL,
  `views` INT(11) NULL DEFAULT NULL,
  `categoria_id` INT(11),
  `usuario_id` INT(11),
  PRIMARY KEY (`id`),
  INDEX `fk_post_categoria_idx` (`categoria_id` ASC),
  INDEX `fk_post_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_post_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `blog`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `blog`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
